build: off

cache:
  - '%LOCALAPPDATA%\pip\Cache'

environment:
  IMGAUG_NO_CV2_INSTALLED_CHECK: 'TRUE'

  matrix:
    - PYTHON: 'C:\Python27-x64'
    - PYTHON: 'C:\Python35-x64'
      INSTALL_PYTORCH_WHEEL: 'TRUE'
    - PYTHON: 'C:\Python36-x64'
      INSTALL_PYTORCH_WHEEL: 'TRUE'
    - PYTHON: 'C:\Python37-x64'
      INSTALL_PYTORCH_WHEEL: 'TRUE'
    - PYTHON: 'C:\Python38-x64'

install:
  - '%PYTHON%\python.exe -m pip install -U pip wheel setuptools'
  - 'if defined INSTALL_PYTORCH_WHEEL %PYTHON%\python.exe -m pip install torch==1.3.0+cpu torchvision==0.4.1+cpu -f https://download.pytorch.org/whl/torch_stable.html'
  - '%PYTHON%\python.exe -m pip install .[tests]'
  - '%PYTHON%\python.exe -m pip install "pydocstyle<4.0.0" flake8 flake8-docstrings'

test_script:
  - '%PYTHON%\python.exe -m pytest'
  - '%PYTHON%\python.exe -m flake8'
